from pydantic import BaseModel, Field, GetJsonSchemaHandler
from pydantic.json_schema import JsonSchemaValue
from pydantic_core import core_schema
from typing import List, Dict, Optional, Any
from datetime import datetime
from bson import ObjectId

class PyObjectId(ObjectId):
    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: Any, handler: Any
    ) -> core_schema.CoreSchema:
        return core_schema.json_or_python_schema(
            json_schema=core_schema.str_schema(),
            python_schema=core_schema.union_schema([
                core_schema.is_instance_schema(ObjectId),
                core_schema.chain_schema([
                    core_schema.str_schema(),
                    core_schema.no_info_plain_validator_function(cls.validate),
                ])
            ]),
            serialization=core_schema.plain_serializer_function_ser_schema(
                lambda x: str(x)
            ),
        )

    @classmethod
    def validate(cls, v):
        if isinstance(v, ObjectId):
            return v
        if isinstance(v, str):
            if ObjectId.is_valid(v):
                return ObjectId(v)
            raise ValueError("Invalid ObjectId")
        raise ValueError("Invalid ObjectId")

    @classmethod
    def __get_pydantic_json_schema__(
        cls, _core_schema: core_schema.CoreSchema, handler: GetJsonSchemaHandler
    ) -> JsonSchemaValue:
        return {"type": "string"}

class TestCase(BaseModel):
    input: str
    expected_output: str
    is_hidden: bool = False

class StarterCode(BaseModel):
    language: str
    code: str

class FunctionParameter(BaseModel):
    """Defines a function parameter"""
    name: str           # e.g., "arr", "data"
    type: str           # e.g., "numpy.ndarray", "pandas.DataFrame"

class FunctionSignature(BaseModel):
    """Defines the expected function signature for code wrapping"""
    name: str                           # e.g., "normalize_data", "plot_histogram"
    parameters: List[FunctionParameter] # Function parameters
    return_type: str                    # e.g., "numpy.ndarray", "matplotlib.figure.Figure"

class Example(BaseModel):
    """A single example with input, output, and optional explanation"""
    input: str              # e.g., "arr = np.array([1, 2, 3, 4, 5])"
    output: str             # e.g., "array([0.2, 0.4, 0.6, 0.8, 1.0])"
    explanation: Optional[str] = None  # e.g., "Normalized using min-max scaling"

class DatasetSchemaColumn(BaseModel):
    """Dataset schema column definition"""
    name: str
    type: str  # "int", "float", "string", "bool"

class DatasetInfo(BaseModel):
    """Dataset information for AIML questions"""
    data_schema: List[DatasetSchemaColumn] = Field(alias="schema")
    rows: List[List[Any]]  # Array of arrays, each inner array is a row
    
    model_config = {
        "populate_by_name": True,
    }

class AssessmentMetadata(BaseModel):
    """Assessment metadata for new format questions"""
    skill: str
    topic: Optional[str] = None
    libraries: List[str] = []
    selected_dataset_format: str = "csv"

class Question(BaseModel):
    id: Optional[PyObjectId] = Field(default_factory=PyObjectId, alias="_id")
    title: str
    
    # LeetCode-style 3-part description (legacy format)
    description: str                    # Problem statement (Markdown)
    examples: List[Example] = []        # Input/Output examples (legacy)
    constraints: List[str] = []        # e.g., ["Use numpy for array operations", "No loops allowed"]
    
    # New format fields
    tasks: List[str] = []               # List of tasks to perform (new format)
    question_type: Optional[str] = None  # e.g., "aiml_coding"
    execution_environment: Optional[str] = None  # e.g., "jupyter_notebook"
    
    difficulty: str  # easy, medium, hard
    languages: List[str] = ["python3"]  # Default to Python for AIML
    public_testcases: List[TestCase]
    hidden_testcases: List[TestCase]
    starter_code: Dict[str, str]  # {language: code}
    
    # AIML-specific fields
    library: str = "numpy"  # numpy, matplotlib, pandas, scikit-learn, etc.
    requires_dataset: bool = False  # True if question needs a dataset (manual creation), False for AI-generated
    dataset_path: Optional[str] = None  # Path to dataset file if requires_dataset is True
    ai_generated: bool = False  # True if generated by AI, False if manually created
    
    # New format: assessment metadata
    assessment_metadata: Optional[Dict[str, Any]] = None  # Contains skill, topic, libraries, selected_dataset_format
    
    # New format: dataset (format-agnostic)
    dataset: Optional[Dict[str, Any]] = None  # Contains schema and rows
    
    # Function signature for code wrapping (optional)
    function_signature: Optional[FunctionSignature] = None
    # If True, user code will be validated and wrapped
    secure_mode: bool = False
    # Admin-defined wrapper template for code execution
    wrapper_template: Optional[str] = None
    is_published: bool = False  # Whether question is visible to users
    created_by: Optional[str] = None  # User ID who created the question
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    model_config = {
        "populate_by_name": True,
        "arbitrary_types_allowed": True,
        "json_encoders": {ObjectId: str},
    }

class QuestionCreate(BaseModel):
    title: str
    # LeetCode-style 3-part description (legacy format)
    description: str                    # Problem statement
    examples: Optional[List[Example]] = []        # Input/Output examples (legacy) - optional
    constraints: Optional[List[str]] = []         # Constraints - optional
    
    # New format fields
    tasks: Optional[List[str]] = []               # List of tasks to perform (new format) - optional
    question_type: Optional[str] = None  # e.g., "aiml_coding"
    execution_environment: Optional[str] = None  # e.g., "jupyter_notebook"
    
    difficulty: Optional[str] = "medium"  # Optional, defaults to medium
    languages: Optional[List[str]] = ["python3"]
    public_testcases: Optional[List[TestCase]] = []  # Optional for manual creation
    hidden_testcases: Optional[List[TestCase]] = []  # Optional for manual creation
    starter_code: Optional[Dict[str, str]] = {}  # Optional for manual creation
    
    # AIML-specific fields
    library: Optional[str] = "numpy"  # Optional, defaults to numpy
    requires_dataset: Optional[bool] = False
    dataset_path: Optional[str] = None
    ai_generated: Optional[bool] = False
    
    # New format: assessment metadata
    assessment_metadata: Optional[Dict[str, Any]] = None
    
    # New format: dataset (format-agnostic)
    dataset: Optional[Dict[str, Any]] = None
    
    function_signature: Optional[FunctionSignature] = None
    secure_mode: Optional[bool] = False
    wrapper_template: Optional[str] = None
    is_published: Optional[bool] = False

class QuestionUpdate(BaseModel):
    title: Optional[str] = None
    # LeetCode-style 3-part description (legacy format)
    description: Optional[str] = None
    examples: Optional[List[Example]] = None
    constraints: Optional[List[str]] = None
    
    # New format fields
    tasks: Optional[List[str]] = None
    question_type: Optional[str] = None
    execution_environment: Optional[str] = None
    
    difficulty: Optional[str] = None
    languages: Optional[List[str]] = None
    public_testcases: Optional[List[TestCase]] = None
    hidden_testcases: Optional[List[TestCase]] = None
    starter_code: Optional[Dict[str, str]] = None
    
    # AIML-specific fields
    library: Optional[str] = None
    requires_dataset: Optional[bool] = None
    dataset_path: Optional[str] = None
    ai_generated: Optional[bool] = None
    
    # New format: assessment metadata
    assessment_metadata: Optional[Dict[str, Any]] = None
    
    # New format: dataset (format-agnostic)
    dataset: Optional[Dict[str, Any]] = None
    
    function_signature: Optional[FunctionSignature] = None
    secure_mode: Optional[bool] = None
    wrapper_template: Optional[str] = None
    is_published: Optional[bool] = None

